### ISSUE TITLE
Async/await confusion

### ISSUE THREAD

**Issue by magnas35** [drewmccormack/SwiftCloudDrive#1]
Hi 

I hope you don't mind me asking but do you have a simple, example project you'd be willing to share?  I'm tying myself in knots trying to setup a CloudDrive. If I try as a View property I get _'async' call cannot occur in a property initializer_ and if I try to use an ObservableObject I hit closure capturing 'self' hell.

I know this exposes my lack of async knowledge but I can't help wondering if I'm just being particularly dumb today as you describe it as a **simple** wrapper. No worries if I am being dumb, simple is relative I suppose, heh.

Thanks

Neil

**Comment by drewmccormack** [comment]
Indeed, the nature of iCloud means all the calls are async. This is because it can block to wait for a download from the cloud, for example.

In SwiftUI, it means you either have to use the .task modifier, or you have to wrap the creation in a Task { } block.

Eg. 
```swift
Task {
    self.drive = try await CloudDrive(ubiquityContainerIdentifier: Self.containerIdentifier, relativePathToRootInContainer: "Audio")
}
```

or 

```swift
ContentView()
    .task {
         self.drive = try await CloudDrive(ubiquityContainerIdentifier: Self.containerIdentifier, relativePathToRootInContainer: "Audio")
    }
```

You could put the drive in an observable object, and use Task to make calls to it. That's how I do it. I have a `Store` observable object, which uses the drive to save files. Of course, the store will then also have mostly async methods.

**Comment by drewmccormack** [comment]
I'll see if I can throw together a simple sample project. Stay tuned...

**Comment by drewmccormack** [comment]
OK, I have added a sample app in the Samples folder of version 1.0.5. Let me know if there is a problem.

**Comment by magnas35** [comment]
Many thanks for the sample. Works as expected except the _cloudDriveDidChange(rootRelativePaths:_doesn't seem to be called when a change is made. Each fresh run picks up the edits which is enough for my needs. Thanks again.

**Comment by drewmccormack** [comment]
Are you testing that cloudDriveDidChange by making changes on a different device? I think it will only trigger if remote changes are made, not changes you make locally.

**Comment by magnas35** [comment]
I initially installed the app onto the sim and saved some text and then installed onto the two real devices. They launched and picked up the correct text. No change made to the text (on any of the three) is being picked up live by the others. If only changes made on the sim should be propagated to the real devices then I can't rule out that Xcode's 'trigger iCloud sync' may be playing up again.
