### ISSUE TITLE
contentsOfDirectory twice in a row fails

### ISSUE THREAD

**Issue by aehlke** [drewmccormack/SwiftCloudDrive#4]
Not sure what I'm missing, but the first time I call `contentsOfDirectory` on an iCloud container it works perfectly, but calling it again immediately after (two lines in a row) fails with the "operation not permitted" error you'd expect when you haven't coordinated access. Any ideas?

edit: I think this might be the issue, https://stackoverflow.com/a/54244695 the startAccessingSecurityScopedResource call can return false in which case the corresponding stop function should not be called however this repo calls it regardless. I'll update in my fork. Thanks

**Comment by drewmccormack** [comment]
OK, let me know. If you put in a PR, I'll take a look.

**Comment by aehlke** [comment]
Thanks for merging
