### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by Roger-Blinto** [drewmccormack/SwiftCloudDrive#8]
Greetings!
It's quite common for old fashioned synchronous code to use Task objects to call async functions and have some kind of blocking mechanism, such as semaphores or synchronous queues, to deliver results to the invoking thread.
The latest changes, in commit edf7e87, causes a deadlock with such architecture, if the main thread tries to initialize SwiftCloudDrive in such a manner. The reason is that the library now also requires synchronous operations on the main thread (Actor) while setting up the MetadataMonitor. Previously initialization could be done on an arbitrary thread and the start of the MetaDataQuery in your library was postponed by an async block on the main thread.
Do you think it is possible to do the initialization in a slightly different way than now, not doing synchronous operations on the main thread?

**Comment by drewmccormack** [comment]
I assume that commit was not what you intended. Seems to be an old one. The problem you have is with the new @MainActor on the startMonitoring... func, right?

I have just pushed a new version that works more like it did before, removing @MainActor, except on the `start` call. 

Even having done that, I'm not sure I would consider the commit flawed. I think it was not wrong to apply the @MainActor to the setup in this case. 

It's probably better to avoid using semaphores like you are to block threads. Better to embrace the async aspect, and just setup a callback or such. Otherwise you will get deadlocks like this one way or the other.

**Comment by Roger-Blinto** [comment]
Much better!
Thanks for your effort!
/Roger

**Comment by Roger-Blinto** [comment]
I agree that the async design should be preferred, but it can be a huge task to implement it in large legacy code bases.

However for initialization methods asynchronous interfaces can be cumbersome. This made me look a second time in your library. How come the functions in FileManager+Coordination.swift are async? None of them do any await calls. It they are changed into plain throwing functions it seems like the init method can be made synchronous too.
Or am I missing something here?

Best regards!
/Roger

**Comment by drewmccormack** [comment]
The file coordination methods can block. They are locking methods, and if another process has the lock, they can halt for seconds. You should not call them on the main thread. They are an old API, so not async. I chose to wrap them in async.

**Comment by Roger-Blinto** [comment]
Yes, sure. They block the calling thread and might take a considerable amount of time. Because of that some background thread should invoke them. However their async interface does nothing and callers have to adopt to it. I will send you a pull request with a non async init and file functions. We prefer such an interface for our fork, it’s up to you to make the decision for the upstream branch. 🙂Best regards!/Roger. Skickat från min iPhone12 juni 2024 kl. 22:03 skrev Drew McCormack ***@***.***>:﻿
The file coordination methods can block. They are locking methods, and if another process has the lock, they can halt for seconds. You should not call them on the main thread. They are an old API, so not async. I chose to wrap them in async.

**Comment by drewmccormack** [comment]
Forcing someone to use a background thread is the old way of doing things. I've adopted a modern swift approach in this library, with Swift concurrency. 

Making the calls async absolutely does do something, it stops the thread blocking. You can call it from the main thread, or any thread, and it won't block.

**Comment by Roger-Blinto** [comment]
> Forcing someone to use a background thread is the old way of doing things. I've adopted a modern swift approach in this library, with Swift concurrency.
> 
Not forcing, it is up to the caller. It can’t be a requirement to make all functions async in modern Swift concurrency.
> Making the calls async absolutely does do something, it stops the thread blocking. You can call it from the main thread, or any thread, and it won't block.
> 
I guess there might be a context switch before the function is invoked, but when it is the calling thread will be blocked at the coordinator call.

**Comment by drewmccormack** [comment]
Yes, you are right. I think I am going to put those coordinator methods on an actor. I believe I originally did that, and accidentally make it a class later without thinking. You are correct that it can currently block.
